env:
  TERM: xterm-256color

colors:
  # Default colors
  primary:
    background: "#1e2127"
    foreground: "#D8DEE9"

  # Normal colors
  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#abb2bf"

  # Bright colors
  bright:
    black: "#5c6370"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#ECEFF4"

font:
  normal:
    family: FiraCode Nerd font
    style: Retina
  bold:
    family: FiraCode Nerd font
    style: Bold
  bold_italic:
    family: FiraCode Nerd font
    style: Bold Italic
  italic:
    family: FiraCode Nerd font
    style: Italic
  offset:
    x: 0
    y: 0

  size: 12.0
  use_thin_strokes: true

window:
  opacity: 0.8
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000

draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: true
