general.import = ["alacritty-theme/themes/gruvbox_dark.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-t", "base"]

[window]
# decorations = "none"
decorations_theme_variant = "dark"
# startup_mode = "Maximized"
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.8
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 12
